version: "3.7"
services:
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    #networks:
      #- default
    
volumes:
  data:
networks: 
  default: 
    external: 
      name: cognizantnetwork
